### ISSUE TITLE
Need help with broken ic

### ISSUE THREAD

**Issue by 4dvn** [CodeFetch/router-u-boot#5]
My winbond W25Q128FVSSIG rom had been broken, how can i reflash the new chip with u-boot?

**Comment by CodeFetch** [comment]
Not at all. The program/U-Boot is the entry point for your device. If your flash is broken, how do you plan to run U-Boot from it?
You should use an external SPI flash writer to write the flash chip directly.

**Comment by 4dvn** [comment]
My router is gl-inet ar150, i just buy it today and the ch341 programmer

**Comment by CodeFetch** [comment]
Ah now I understand you... I close this issue as it is not specific to the software.

You just need to put the [U-Boot image](http://projects.dymacz.pl/u-boot_mod/u-boot_mod__gl-inet_gl-ar150__20180223__git_master-7a540a78.bin) at the beginning of the flash. The problem is that you're missing the ART partition. Ask e.g. in the OpenWrt forum for an ART dump of a GL-AR150, but be aware that the radio performance could be worse than before and your router might behave unfair causing interferences which also voids conformity.

**Comment by 4dvn** [comment]
> Ah now I understand you... I close this issue as it is not specific to the software.
> 
> You just need to put the [U-Boot image](http://projects.dymacz.pl/u-boot_mod/u-boot_mod__gl-inet_gl-ar150__20180223__git_master-7a540a78.bin) at the beginning of the flash. The problem is that you're missing the ART partition. Ask e.g. in the OpenWrt forum for an ART dump of a GL-AR150, but be aware that the radio performance could be worse than before and your router might behave unfair causing interferences which also voids conformity.

Is working, i sent request to gl-inet and they give me the art file, thank you!
